[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 30
healthcheckInterval = 10
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
startCommand = "./start.sh"
minInstances = 1
maxInstances = 10

[env]
PYTHONPATH = "/app"
PORT = "8000"
ENVIRONMENT = "production"
DEBUG = "false"
# Supabase Configuration - CRITICAL for newsletter API
# SECURITY: These values MUST be set via Railway environment variables
# NEVER hardcode production URLs or keys in this file
SUPABASE_URL = "${{ SUPABASE_URL }}"
SUPABASE_SERVICE_KEY = "${{ SUPABASE_SERVICE_KEY }}"
# SECURITY CRITICAL: Secret key must be set via Railway environment variables
SECRET_KEY = "${{ SECRET_KEY }}"
# SECURITY CRITICAL: Database URL must be set via Railway environment variables
DATABASE_URL = "${{ DATABASE_URL }}"
WORKERS = "2"
# Performance optimizations
WORKER_TIMEOUT = "30"
WORKER_KEEPALIVE = "5"
WORKER_MAX_REQUESTS = "1000"
WORKER_MAX_REQUESTS_JITTER = "50"
PROJECT_NAME = "aclue API"
VERSION = "1.0.0"
HOST = "0.0.0.0"
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = "30"
REFRESH_TOKEN_EXPIRE_DAYS = "30"
ML_BATCH_SIZE = "32"
ML_UPDATE_INTERVAL_MINUTES = "5"
ENABLE_REGISTRATION = "true"
ENABLE_ML_RECOMMENDATIONS = "true"
ENABLE_AFFILIATE_TRACKING = "true"
MAX_RECOMMENDATIONS_PER_USER = "50"
MAX_SWIPES_PER_SESSION = "50"
COMMISSION_RATE_DEFAULT = "0.075"
# Security and performance configuration
ALLOWED_HOSTS = "aclue.app,www.aclue.app,aclue.co.uk,www.aclue.co.uk,api.aclue.app,aclue-backend-production.up.railway.app"
RATE_LIMIT_PER_MINUTE = "60"
RATE_LIMIT_BURST = "100"
# Monitoring and observability
PROMETHEUS_ENABLED = "true"
LOG_LEVEL = "INFO"
# Health check configuration
HEALTH_CHECK_INTERVAL = "30"