[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.prod"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
startCommand = "./start.sh"

[env]
PYTHONPATH = "/app"
PORT = "8000"
ENVIRONMENT = "production"
DEBUG = "false"
WORKERS = "4"
PROJECT_NAME = "GiftSync API"
VERSION = "1.0.0"
HOST = "0.0.0.0"
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = "30"
REFRESH_TOKEN_EXPIRE_DAYS = "30"
ML_BATCH_SIZE = "32"
ML_UPDATE_INTERVAL_MINUTES = "5"
ENABLE_REGISTRATION = "true"
ENABLE_ML_RECOMMENDATIONS = "true"
ENABLE_AFFILIATE_TRACKING = "true"
MAX_RECOMMENDATIONS_PER_USER = "50"
MAX_SWIPES_PER_SESSION = "50"
COMMISSION_RATE_DEFAULT = "0.075"
RATE_LIMIT_PER_MINUTE = "60"
RATE_LIMIT_BURST = "100"
PROMETHEUS_ENABLED = "true"