name: aclue_app
description: aclue - AI-powered gift recommendation platform
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # Navigation
  go_router: ^13.2.0

  # Networking
  dio: ^5.4.0
  retrofit: ^4.0.3
  json_annotation: ^4.8.1

  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # UI Components
  flutter_animate: ^4.3.0
  lottie: ^2.7.0
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9

  # Gestures & Animations
  flutter_card_swiper: ^6.0.0
  flutter_staggered_animations: ^1.1.1

  # Authentication
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  google_sign_in: ^6.1.6

  # Analytics
  firebase_analytics: ^10.7.4
  mixpanel_flutter: ^2.2.0

  # Push Notifications
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^16.3.2

  # Utilities
  url_launcher: ^6.2.2
  share_plus: ^7.2.2
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.6
  device_info_plus: ^9.1.1
  package_info_plus: ^4.2.0

  # Permissions
  permission_handler: ^11.1.0

  # Biometric Authentication
  local_auth: ^2.1.7

  # Image Handling
  image_picker: ^1.0.4
  flutter_image_compress: ^2.1.0

  # Internationalization
  intl: ^0.18.1
  flutter_localizations:
    sdk: flutter

  # WebSocket
  web_socket_channel: ^2.4.0

  # Logging
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^3.0.0

  # Code Generation
  build_runner: ^2.4.7
  retrofit_generator: ^8.0.4
  riverpod_generator: ^2.3.9
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1

  # Testing
  mockito: ^5.4.4
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700