apiVersion: v1
kind: Secret
metadata:
  name: giftsync-secrets
  namespace: giftsync
type: Opaque
data:
  # Base64 encoded values - use: echo -n 'your-value' | base64
  database-url: # echo -n 'postgresql://user:pass@host:5432/db' | base64
  secret-key: # echo -n 'your-secret-key' | base64
  jwt-secret: # echo -n 'your-jwt-secret' | base64
  redis-url: # echo -n 'redis://host:6379' | base64
  aws-access-key: # echo -n 'your-aws-access-key' | base64
  aws-secret-key: # echo -n 'your-aws-secret-key' | base64
  mixpanel-token: # echo -n 'your-mixpanel-token' | base64
  sentry-dsn: # echo -n 'your-sentry-dsn' | base64