global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'aclue-monitor'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  - "rules/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'

  # Node Exporter - System metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          service: 'node-exporter'

  # Docker containers metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          service: 'cadvisor'

  # Frontend (Next.js) metrics
  - job_name: 'frontend'
    metrics_path: '/api/metrics'
    static_configs:
      - targets: ['aclue.app']
        labels:
          service: 'nextjs'
          environment: 'production'

  # Backend (FastAPI) metrics
  - job_name: 'backend'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['aclue-backend-production.up.railway.app']
        labels:
          service: 'fastapi'
          environment: 'production'

  # PostgreSQL metrics (via postgres_exporter)
  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgres-exporter:9187']
        labels:
          service: 'postgresql'
          database: 'aclue'

  # Redis metrics (if using Redis)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
        labels:
          service: 'redis'

  # Blackbox Exporter - Endpoint monitoring
  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - https://aclue.app
          - https://aclue.co.uk
          - https://aclue-backend-production.up.railway.app/health
        labels:
          type: 'endpoint'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115