# Detect-Secrets Configuration for Aclue Infrastructure
# Comprehensive secret detection baseline configuration

version: "1.5.0"

filters_used:
  - filename:
      # Skip certain file types that commonly have false positives
      - ".git/*"
      - "node_modules/*"
      - "venv/*"
      - ".venv/*"
      - "__pycache__/*"
      - "*.pyc"
      - ".next/*"
      - "dist/*"
      - "build/*"
      - "coverage/*"
      - ".vercel/*"
      - ".railway/*"
      - "package-lock.json"
      - "yarn.lock"
      - "*.min.js"
      - "*.map"

  # High entropy string detection
  - high_entropy_strings:
      charset: "base64"
      limit: 3.5
  - high_entropy_strings:
      charset: "hex"
      limit: 3.0

  # Keyword-based detection
  - keyword:
      word_list:
        - password
        - passwd
        - pwd
        - secret
        - token
        - key
        - api_key
        - apikey
        - access_key
        - secret_key
        - private_key
        - auth_token
        - bearer_token
        - jwt_secret
        - database_url
        - db_url
        - connection_string
        - oauth_token
        - refresh_token
        - webhook_secret
        - encryption_key
        - signing_key

  # Specific secret types
  - aws_key_id:
  - basic_auth:
  - cloudant:
  - db2:
  - github:
  - gitlab:
  - jwt:
  - mailchimp:
  - private_key:
  - slack:
  - softlayer:
  - square_oauth:
  - stripe:
  - trello:
  - twilio:

# Custom plugins (if available)
plugins_used:
  - name: "AWSKeyDetector"
  - name: "ArtifactoryDetector"
  - name: "AzureStorageKeyDetector"
  - name: "Base64HighEntropyString"
    limit: 4.5
  - name: "BasicAuthDetector"
  - name: "CloudantDetector"
  - name: "DiscordBotTokenDetector"
  - name: "GitHubTokenDetector"
  - name: "HexHighEntropyString"
    limit: 3.0
  - name: "IbmCloudIamDetector"
  - name: "IbmCosHmacDetector"
  - name: "JwtTokenDetector"
  - name: "KeywordDetector"
    keyword_exclude: |
      example
      test
      dummy
      fake
      placeholder
      sample
      template
      localhost
      127.0.0.1
  - name: "MailchimpDetector"
  - name: "NpmDetector"
  - name: "PrivateKeyDetector"
  - name: "SendGridDetector"
  - name: "SlackDetector"
  - name: "SoftlayerDetector"
  - name: "SquareOAuthDetector"
  - name: "StripeDetector"
  - name: "TwilioKeyDetector"

# Results configuration
results: {}

# Exclude patterns
exclude:
  files: |
    .*\.md$
    .*\.txt$
    .*\.log$
    package-lock\.json$
    yarn\.lock$
    .*\.min\.js$
    .*\.map$