# AlertManager configuration for aclue monitoring
global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'alerts@aclue.app'
  smtp_auth_username: 'alerts@aclue.app'
  smtp_auth_password: 'your-smtp-password'

# Alert routing tree
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default'

  routes:
    # Critical alerts - immediate notification
    - match:
        severity: critical
      receiver: 'critical'
      group_wait: 0s
      repeat_interval: 15m

    # Warning alerts - batched
    - match:
        severity: warning
      receiver: 'warning'
      group_wait: 5m
      group_interval: 5m
      repeat_interval: 30m

    # Business metrics - daily summary
    - match:
        category: business
      receiver: 'business'
      group_wait: 30m
      group_interval: 30m
      repeat_interval: 24h

    # Security alerts - immediate
    - match:
        category: security
      receiver: 'security'
      group_wait: 0s
      repeat_interval: 10m

# Alert receivers
receivers:
  - name: 'default'
    email_configs:
      - to: 'team@aclue.app'
        send_resolved: true

  - name: 'critical'
    email_configs:
      - to: 'oncall@aclue.app'
        send_resolved: true
        headers:
          Subject: '🚨 CRITICAL: {{ .GroupLabels.alertname }} on {{ .GroupLabels.service }}'
    slack_configs:
      - api_url: 'YOUR_SLACK_WEBHOOK_URL'
        channel: '#alerts-critical'
        title: 'Critical Alert'
        text: '{{ range .Alerts }}{{ .Annotations.summary }}\n{{ .Annotations.description }}{{ end }}'
    pagerduty_configs:
      - service_key: 'YOUR_PAGERDUTY_KEY'
        description: '{{ .GroupLabels.alertname }}'

  - name: 'warning'
    email_configs:
      - to: 'dev@aclue.app'
        send_resolved: true
    slack_configs:
      - api_url: 'YOUR_SLACK_WEBHOOK_URL'
        channel: '#alerts-warning'
        title: 'Warning Alert'
        text: '{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'

  - name: 'business'
    email_configs:
      - to: 'business@aclue.app'
        send_resolved: false
        headers:
          Subject: '📊 Business Metrics Alert: {{ .GroupLabels.alertname }}'

  - name: 'security'
    email_configs:
      - to: 'security@aclue.app'
        send_resolved: true
        headers:
          Subject: '🔒 SECURITY: {{ .GroupLabels.alertname }}'
    slack_configs:
      - api_url: 'YOUR_SLACK_WEBHOOK_URL'
        channel: '#security-alerts'
        title: 'Security Alert'
        text: '{{ range .Alerts }}{{ .Annotations.summary }}\n{{ .Annotations.description }}{{ end }}'

# Inhibition rules
inhibit_rules:
  # Inhibit warning alerts if critical alert is firing for same service
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'service']

  # Inhibit info alerts if warning or critical is firing
  - source_match_re:
      severity: 'critical|warning'
    target_match:
      severity: 'info'
    equal: ['alertname', 'service']
