# Blackbox Exporter configuration for endpoint monitoring
modules:
  http_2xx:
    prober: http
    timeout: 10s
    http:
      valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
      valid_status_codes: [200, 201, 202, 203, 204, 301, 302, 303, 307, 308]
      method: GET
      follow_redirects: true
      fail_if_ssl: false
      fail_if_not_ssl: true
      tls_config:
        insecure_skip_verify: false
      preferred_ip_protocol: "ip4"
      ip_protocol_fallback: true

  http_post_2xx:
    prober: http
    timeout: 10s
    http:
      valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
      valid_status_codes: [200, 201, 202, 204]
      method: POST
      headers:
        Content-Type: application/json
      body: '{}'
      fail_if_ssl: false
      fail_if_not_ssl: true

  http_401:
    prober: http
    timeout: 10s
    http:
      valid_status_codes: [401]
      method: GET

  tcp_connect:
    prober: tcp
    timeout: 10s

  dns_check:
    prober: dns
    timeout: 10s
    dns:
      query_name: "aclue.app"
      query_type: "A"
      valid_rcodes:
        - NOERROR

  icmp_check:
    prober: icmp
    timeout: 10s
    icmp:
      preferred_ip_protocol: "ip4"

  ssl_cert_check:
    prober: http
    timeout: 10s
    http:
      method: GET
      fail_if_ssl: false
      fail_if_not_ssl: true
      tls_config:
        insecure_skip_verify: false
