# OWASP ZAP Configuration for Automated Penetration Testing
# Docker-based security scanning with baseline and full scans

env:
  contexts:
    - name: "Aclue Production"
      urls:
        - "https://aclue.app"
        - "https://aclue-backend-production.up.railway.app"
      includePaths:
        - "https://aclue.app/*"
        - "https://aclue-backend-production.up.railway.app/*"
      excludePaths:
        - ".*\\.js"
        - ".*\\.css"
        - ".*\\.png"
        - ".*\\.jpeg"
        - ".*\\.jpg"
        - ".*\\.gif"
        - ".*\\.svg"
      authentication:
        method: "json"
        parameters:
          loginUrl: "https://aclue-backend-production.up.railway.app/api/v1/auth/login"
          loginRequestData: '{"email":"john.doe@example.com","password":"password123"}'
          usernameParameter: "email"
          passwordParameter: "password"
          loggedInRegex: "access_token"
          loggedOutRegex: "login"

    - name: "Aclue Development"
      urls:
        - "http://localhost:3000"
        - "http://localhost:8000"
      includePaths:
        - "http://localhost:3000/*"
        - "http://localhost:8000/*"
      authentication:
        method: "json"
        parameters:
          loginUrl: "http://localhost:8000/api/v1/auth/login"
          loginRequestData: '{"email":"john.doe@example.com","password":"password123"}'

jobs:
  - type: passiveScan-config
    parameters:
      maxAlertsPerRule: 10
      scanOnlyInScope: true

  - type: spider
    parameters:
      maxDuration: 60
      maxDepth: 10
      maxChildren: 10
      acceptCookies: true
      handleODataParametersVisited: false
      handleParameters: "use_all"
      maxParseSizeBytes: 2621440
      parseComments: true
      parseGit: false
      parseRobotsTxt: true
      parseSVNEntries: false
      parseSitemapXml: true
      postForm: true
      processForm: true
      requestWaitTime: 200
      sendRefererHeader: true
      threadCount: 5
      userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"

  - type: ajaxSpider
    parameters:
      maxDuration: 60
      maxCrawlDepth: 10
      browserId: "chrome-headless"
      clickDefaultElems: true
      clickElemsOnce: false
      eventWait: 1000
      maxCrawlStates: 0
      randomInputs: false
      reloadWait: 1000
      windowId: ""

  - type: passiveScan-wait
    parameters:
      maxDuration: 300

  - type: activeScan
    parameters:
      maxDuration: 120
      maxRuleDurationInMins: 5
      maxScanDurationInMins: 120
      delayInMs: 0
      handleAntiCSRFTokens: true
      injectPluginIdInHeader: false
      scanHeadersAllRequests: false
      threadPerHost: 2
      policy: "Default Policy"
      defaultPolicy: "Default Policy"
      policyDefinition:
        defaultStrength: "medium"
        defaultThreshold: "medium"
        rules:
          - id: 10003  # User Agent Fuzzer
            strength: "high"
            threshold: "low"
          - id: 10012  # Cross Site Request Forgery
            strength: "high"
            threshold: "low"
          - id: 10015  # Heartbleed OpenSSL Vulnerability
            strength: "high"
            threshold: "low"
          - id: 10016  # Web Browser XSS Protection Not Enabled
            strength: "high"
            threshold: "low"
          - id: 10017  # Cross-Domain JavaScript Source File Inclusion
            strength: "high"
            threshold: "low"
          - id: 10019  # Content-Type Header Missing
            strength: "high"
            threshold: "low"
          - id: 10020  # X-Frame-Options Header
            strength: "high"
            threshold: "low"
          - id: 10021  # X-Content-Type-Options Header Missing
            strength: "high"
            threshold: "low"
          - id: 10023  # Information Disclosure - Debug Error Messages
            strength: "high"
            threshold: "low"
          - id: 10024  # Information Disclosure - Sensitive Information in URL
            strength: "high"
            threshold: "low"
          - id: 10025  # Information Disclosure - Sensitive Information in HTTP Referrer Header
            strength: "high"
            threshold: "low"
          - id: 10027  # Information Disclosure - Suspicious Comments
            strength: "high"
            threshold: "low"
          - id: 10032  # Viewstate
            strength: "high"
            threshold: "low"
          - id: 10040  # Secure Pages Include Mixed Content
            strength: "high"
            threshold: "low"
          - id: 10045  # Source Code Disclosure - /WEB-INF folder
            strength: "high"
            threshold: "low"
          - id: 10048  # Remote Code Execution - Shell Shock
            strength: "high"
            threshold: "low"
          - id: 10055  # CSP
            strength: "high"
            threshold: "low"
          - id: 10056  # X-Debug-Token Information Leak
            strength: "high"
            threshold: "low"
          - id: 10061  # X-AspNet-Version Response Header
            strength: "high"
            threshold: "low"
          - id: 10096  # Timestamp Disclosure
            strength: "high"
            threshold: "low"
          - id: 10098  # Cross-Domain Misconfiguration
            strength: "high"
            threshold: "low"
          - id: 10105  # Weak Authentication Method
            strength: "high"
            threshold: "low"
          - id: 10202  # Absence of Anti-CSRF Tokens
            strength: "high"
            threshold: "low"
          - id: 20019  # External Redirect
            strength: "high"
            threshold: "low"
          - id: 30001  # Buffer Overflow
            strength: "high"
            threshold: "low"
          - id: 30002  # Format String Error
            strength: "high"
            threshold: "low"
          - id: 40003  # CRLF Injection
            strength: "high"
            threshold: "low"
          - id: 40008  # Parameter Tampering
            strength: "high"
            threshold: "low"
          - id: 40009  # Server Side Include
            strength: "high"
            threshold: "low"
          - id: 40012  # Cross Site Scripting (Reflected)
            strength: "high"
            threshold: "low"
          - id: 40013  # Session Fixation
            strength: "high"
            threshold: "low"
          - id: 40014  # Cross Site Scripting (Persistent)
            strength: "high"
            threshold: "low"
          - id: 40016  # Cross Site Scripting (Persistent) - Prime
            strength: "high"
            threshold: "low"
          - id: 40017  # Cross Site Scripting (Persistent) - Spider
            strength: "high"
            threshold: "low"
          - id: 40018  # SQL Injection
            strength: "high"
            threshold: "low"
          - id: 40019  # SQL Injection - Error Based
            strength: "high"
            threshold: "low"
          - id: 40020  # SQL Injection - Time Based
            strength: "high"
            threshold: "low"
          - id: 40021  # SQL Injection - Boolean Based
            strength: "high"
            threshold: "low"
          - id: 40022  # SQL Injection - Hypersonic (Time Based)
            strength: "high"
            threshold: "low"
          - id: 40023  # SQL Injection - Oracle (Time Based)
            strength: "high"
            threshold: "low"
          - id: 40024  # SQL Injection - PostgreSQL (Time Based)
            strength: "high"
            threshold: "low"
          - id: 90001  # Insecure JSF ViewState
            strength: "high"
            threshold: "low"
          - id: 90011  # Charset Mismatch
            strength: "high"
            threshold: "low"
          - id: 90018  # SQL Injection - SQLite
            strength: "high"
            threshold: "low"
          - id: 90019  # Server Side Code Injection
            strength: "high"
            threshold: "low"
          - id: 90020  # Remote OS Command Injection
            strength: "high"
            threshold: "low"
          - id: 90021  # XPath Injection
            strength: "high"
            threshold: "low"
          - id: 90022  # XML External Entity Attack
            strength: "high"
            threshold: "low"
          - id: 90023  # XML Injection
            strength: "high"
            threshold: "low"
          - id: 90024  # Generic Padding Oracle
            strength: "high"
            threshold: "low"
          - id: 90025  # Expression Language Injection
            strength: "high"
            threshold: "low"
          - id: 90028  # Insecure HTTP Method
            strength: "high"
            threshold: "low"
          - id: 90030  # WSDL File Detection
            strength: "high"
            threshold: "low"

  - type: report
    parameters:
      template: "traditional-json"
      reportDir: "/home/jack/Documents/aclue-preprod/tests-22-sept/automated/reports"
      reportFile: "zap-scan-report"
      reportTitle: "Aclue OWASP ZAP Security Scan Report"
      reportDescription: "Automated penetration testing results"
      displayReport: false
    risks:
      - high
      - medium
      - low
      - informational
    confidences:
      - high
      - medium
      - low
      - falsepositive

  - type: outputSummary
    parameters:
      format: "json"
      summaryFile: "/home/jack/Documents/aclue-preprod/tests-22-sept/automated/reports/zap-summary.json"